// Sample data: the four invented cases a new account starts with, and the evidence in each.
// It stands in for what a server would send. Nothing here is read after sign-in except through state.js.

// The case files, in the order they sit in the drawer (back of the drawer first).
// upd is "last updated" (bigger = more recent); sum is the one-line summary on the file; long is the full overview.
const CASES = [
  {
    cf: "CF-0712",
    title: "The Ashcroft Affair",
    place: "Ashcroft House, Belgravia",
    date: "3 March 1958",
    iso: "1958-03-03",
    status: "Active",
    upd: 4,
    sum: "An heiress, an altered will, and a guest list with one name too many.",
    long: "An heiress, an altered will, and a guest list with one name too many. The will was changed nine days before the dinner, and nobody at the table admits to inviting the eleventh guest.",
  },
  {
    cf: "CF-0428",
    title: "Midnight at Bellamy",
    place: "Hotel Bellamy, Mayfair",
    date: "12 November 1961",
    iso: "1961-11-12",
    status: "Under review",
    upd: 3,
    sum: "A night porter’s ledger stops at twelve, and room 9 was never checked out.",
    long: "A night porter’s ledger stops at twelve, and room 9 was never checked out. The key was returned to the desk; the guest was not seen leaving.",
  },
  {
    cf: "CF-1105",
    title: "The Hawthorne Letters",
    place: "Hawthorne & Sons, Fleet Street",
    date: "5 June 1967",
    iso: "1967-06-05",
    status: "Closed",
    upd: 2,
    sum: "Six unsigned letters, one typewriter, and a postmark that cannot be right.",
    long: "Six unsigned letters, one typewriter, and a postmark that cannot be right. The typeface was matched to a machine in the firm’s own post room.",
  },
  {
    cf: "CF-0821",
    title: "A Study in Vermilion",
    place: "Marlowe Gallery, Chelsea",
    date: "21 August 1963",
    iso: "1963-08-21",
    status: "Cold case",
    upd: 1,
    sum: "A vanished portrait, a false provenance, and red pigment where it should not be.",
    long: "A vanished portrait, a false provenance, and red pigment where it should not be. The frame was found re-hung, empty, the morning after the private view.",
  },
];

// Evidence in each sample case. Every piece has a type, a summary and the people, places and objects found
// in it: the folder's Evidence tab shows these, and the pin board's connections graph is built from them.
// This is sample data standing in for files that were uploaded and analysed.
const EVID = {
  "CF-0712": [
    {
      id: "E1",
      type: "witness_statement",
      date: "4 March 1958",
      title: "Statement of the housekeeper",
      summary: "Ten places were laid. An eleventh card was added to the table after the list was typed.",
      people: ["Mrs Dunmore", "Eleanor Ashcroft", "Julian Vane"],
      places: ["Ashcroft House"],
      objects: ["Guest list", "Place cards"],
    },
    {
      id: "E2",
      type: "other",
      date: "22 February 1958",
      title: "Will, as altered",
      summary: "The alteration is initialled but the initials are not the solicitor’s.",
      people: ["Eleanor Ashcroft", "Harold Pym"],
      places: ["Pym & Lowe, Lincoln’s Inn"],
      objects: ["Altered will"],
    },
    {
      id: "E3",
      type: "other",
      date: "3 March 1958",
      title: "Guest list for the dinner",
      summary: "Typed list of ten names, with one more added in ink.",
      people: ["Eleanor Ashcroft", "Julian Vane"],
      places: ["Ashcroft House"],
      objects: ["Guest list"],
    },
    {
      id: "E4",
      type: "communication",
      date: "24 February 1958",
      title: "Letter from the solicitor",
      summary: "Pym writes that he was not present when the will was changed.",
      people: ["Harold Pym", "Eleanor Ashcroft"],
      places: ["Pym & Lowe, Lincoln’s Inn"],
      objects: ["Altered will"],
    },
    {
      id: "E5",
      type: "crime_scene_evidence",
      date: "3 March 1958",
      title: "Photograph of the dining table",
      summary: "Eleven place cards are visible; one is in a different hand.",
      people: ["Julian Vane"],
      places: ["Ashcroft House"],
      objects: ["Place cards"],
    },
    {
      id: "E6",
      type: "witness_statement",
      date: "6 March 1958",
      title: "Statement of Julian Vane",
      summary: "Says he was invited by telephone and never saw a written list.",
      people: ["Julian Vane", "Eleanor Ashcroft", "Harold Pym"],
      places: ["Ashcroft House"],
      objects: [],
    },
  ],
  "CF-0428": [
    {
      id: "E1",
      type: "timeline_event",
      date: "12 November 1961",
      title: "Night ledger, pages 40 to 41",
      summary: "Entries stop at midnight and resume at ten past six.",
      people: ["Arthur Coyle"],
      places: ["Front desk"],
      objects: ["Night ledger"],
    },
    {
      id: "E2",
      type: "witness_statement",
      date: "13 November 1961",
      title: "Statement of the night porter",
      summary: "Coyle says the key to room 9 was on the rack when he came back to the desk.",
      people: ["Arthur Coyle", "Lena Hart"],
      places: ["Front desk", "Room 9"],
      objects: ["Room 9 key"],
    },
    {
      id: "E3",
      type: "witness_statement",
      date: "14 November 1961",
      title: "Statement of the relief porter",
      summary: "Reddy covered the desk from midnight and made no entries.",
      people: ["Tom Reddy", "Arthur Coyle"],
      places: ["Front desk"],
      objects: ["Night ledger"],
    },
    {
      id: "E4",
      type: "crime_scene_evidence",
      date: "11 November 1961",
      title: "Laundry ticket for room 9",
      summary: "Collected but never returned to the room.",
      people: ["Lena Hart"],
      places: ["Room 9"],
      objects: ["Laundry ticket"],
    },
    {
      id: "E5",
      type: "crime_scene_evidence",
      date: "13 November 1961",
      title: "Photograph of the key rack",
      summary: "Hook 9 holds a key with a newer tag than the others.",
      people: [],
      places: ["Front desk"],
      objects: ["Room 9 key"],
    },
    {
      id: "E6",
      type: "communication",
      date: "20 November 1961",
      title: "Letter from the manager",
      summary: "Confirms Miss Hart paid a week in advance and left no forwarding address.",
      people: ["Mrs Bell", "Lena Hart"],
      places: ["Hotel Bellamy"],
      objects: [],
    },
  ],
  "CF-1105": [
    {
      id: "E1",
      type: "communication",
      date: "5 June 1967",
      title: "The six unsigned letters",
      summary: "All addressed to the senior partner, all on the firm’s own paper.",
      people: ["Edwin Hawthorne"],
      places: ["Hawthorne & Sons"],
      objects: ["Unsigned letters"],
    },
    {
      id: "E2",
      type: "crime_scene_evidence",
      date: "19 June 1967",
      title: "Typeface comparison report",
      summary: "A worn lower-case e matches the machine kept in the post room.",
      people: ["Peter Nash"],
      places: ["Post room"],
      objects: ["Typewriter", "Unsigned letters"],
    },
    {
      id: "E3",
      type: "crime_scene_evidence",
      date: "7 June 1967",
      title: "Envelope and postmark",
      summary: "Postmarked on a day the sorting office was closed.",
      people: [],
      places: ["Mount Pleasant sorting office"],
      objects: ["Postmarked envelope", "Unsigned letters"],
    },
    {
      id: "E4",
      type: "witness_statement",
      date: "9 June 1967",
      title: "Statement of the post-room clerk",
      summary: "Nash says the typewriter is used by anyone who passes.",
      people: ["Peter Nash", "Edwin Hawthorne"],
      places: ["Post room"],
      objects: ["Typewriter"],
    },
    {
      id: "E5",
      type: "witness_statement",
      date: "9 June 1967",
      title: "Statement of the typist",
      summary: "Miss Calder saw Nash typing after hours twice that month.",
      people: ["Ruth Calder", "Peter Nash"],
      places: ["Hawthorne & Sons"],
      objects: ["Typewriter"],
    },
    {
      id: "E6",
      type: "communication",
      date: "27 June 1967",
      title: "Reply from the Post Office",
      summary: "The date stamp in question was reported missing in May.",
      people: [],
      places: ["Mount Pleasant sorting office"],
      objects: ["Postmarked envelope"],
    },
  ],
  "CF-0821": [
    {
      id: "E1",
      type: "other",
      date: "2 August 1963",
      title: "Provenance papers",
      summary: "Two of the three previous owners cannot be traced.",
      people: ["Mr Lisle", "Clara Marlowe"],
      places: ["Marlowe Gallery"],
      objects: ["Provenance papers", "The portrait"],
    },
    {
      id: "E2",
      type: "crime_scene_evidence",
      date: "30 August 1963",
      title: "Pigment analysis",
      summary: "The red in the sitter’s collar is a modern vermilion.",
      people: ["Anton Reyes"],
      places: ["Restorer’s studio"],
      objects: ["Vermilion pigment", "The portrait"],
    },
    {
      id: "E3",
      type: "crime_scene_evidence",
      date: "21 August 1963",
      title: "Photograph of the empty frame",
      summary: "The frame was re-hung on its own hooks.",
      people: [],
      places: ["Marlowe Gallery"],
      objects: ["Empty frame"],
    },
    {
      id: "E4",
      type: "witness_statement",
      date: "22 August 1963",
      title: "Statement of the gallery owner",
      summary: "Mrs Marlowe locked up herself after the private view.",
      people: ["Clara Marlowe", "Anton Reyes"],
      places: ["Marlowe Gallery"],
      objects: ["Empty frame", "The portrait"],
    },
    {
      id: "E5",
      type: "other",
      date: "20 August 1963",
      title: "Guest book, private view",
      summary: "Lisle signed in twice.",
      people: ["Mr Lisle", "Anton Reyes", "Clara Marlowe"],
      places: ["Marlowe Gallery"],
      objects: [],
    },
    {
      id: "E6",
      type: "other",
      date: "12 July 1963",
      title: "Invoice from the restorer",
      summary: "For cleaning and “minor retouching”, paid by Lisle.",
      people: ["Anton Reyes", "Mr Lisle"],
      places: ["Restorer’s studio"],
      objects: ["Vermilion pigment"],
    },
  ],
};
// Cross-references: two things tied together by reading one piece of evidence against another.
const XREF = {
  "CF-0712": [
    {
      a: "Julian Vane",
      b: "Altered will",
      ev: ["E2", "E6"],
      note: "The initials on the alteration match the signature on Vane’s statement.",
    },
  ],
  "CF-0428": [
    {
      a: "Tom Reddy",
      b: "Room 9 key",
      ev: ["E3", "E5"],
      note: "The new key tag appears during the hours Reddy covered the desk.",
    },
  ],
  "CF-1105": [
    {
      a: "Peter Nash",
      b: "Postmarked envelope",
      ev: ["E4", "E6"],
      note: "The date stamp went missing the month Nash began handling the outgoing post.",
    },
  ],
  "CF-0821": [
    {
      a: "Mr Lisle",
      b: "Vermilion pigment",
      ev: ["E1", "E6"],
      note: "Lisle paid for the retouching weeks before he supplied the provenance.",
    },
  ],
};
